[package]
name = "epub_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
epub = "1.2"
iced = { version = "0.9", features = ["tokio", "async-std"] }
rfd = "0.11"
tokio = { version = "1.0", features = ["full"] }
